compiler:
  solc:
    version: null  # This tells Brownie to infer the version from each contract's pragma statement
  solc_versions:
    0.5.16: {}
    0.8.20: {}
    0.8.19: {}
networks:
  ganache-local:
    host: http://127.0.0.1
    port: 8545
    network_id: 5777
  goerli:
    host: https://goerli.infura.io/ws/v3/${WEB3_INFURA_PROJECT_ID}
    chain_id: 5
dotenv: .env
etherscan:
  token: $ETHERSCAN_TOKEN